name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-flake:
    name: Nixpkgs Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - run: nix-channel --add https://nixos.org/channels/nixos-22.11 nixos 
      - run: nix-channel --update
      - run: nix shell nixpkgs#nixpkgs-fmt -c nixpkgs-fmt . --check
